mysite/urls.py
from django.contrib import admin
from django.urls import path,include



urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('pdf.urls')),
    



   
]

pdf/urls.py
from . import views
from django.urls import path

app_name='pdf'


urlpatterns = [
    path('', views.accept,name='accept'),
    path('<int:id>/', views.resume,name='resume'),
    path("list/",views.list,name="list"),
]

pdf/models.py
from django.db import models

# Create your models here.


class Profile(models.Model):
    name=models.CharField(max_length=200)
    email=models.CharField(max_length=200)
    phone=models.CharField(max_length=200)
    summary=models.TextField(max_length=200)
    degree=models.CharField(max_length=200)
    school=models.CharField(max_length=200)
    university=models.CharField(max_length=200)
    privious_work=models.TextField(max_length=2000)
    skills=models.TextField(max_length=2000)

pdf/views.py
from django.shortcuts import render

from.models import Profile
import pdfkit
from django.http import HttpResponse
from django.template import  loader
import io

# Create your views here.

def accept(request):

    if request.method=="POST":
        name=request.POST.get("name","")
        email=request.POST.get("email","")
        phone=request.POST.get("phone","")
        summary=request.POST.get("summary","")
        degree=request.POST.get("degree","")
        school=request.POST.get("school","")
        university=request.POST.get("university","")
        privious_work=request.POST.get("privious_work","")
        skills=request.POST.get("skills","")

        profile=Profile(name=name,email=email,phone=phone,summary=summary, degree=degree,school=school,university=university,privious_work=privious_work, skills=skills,)
        profile.save()
      
    return render(request,'pdf/accept.html')




def resume(request,id):
    user_profile=Profile.objects.get(pk=id)

    template=loader.get_template('pdf/resume.html')
    html=template.render({"user_profile":user_profile})
    options={
        'page-size':'letter',
        'encoding':'UTF-8',
    }
    pdf=pdfkit.from_string(html,False,options)
    response=HttpResponse(pdf,content_type='application/pdf')
    response['Content-Disposition']='attachment'
    filename="resume.pdf"
    return response



def list(request):
    profiles=Profile.objects.all()

    return render(request,'pdf/list.html',{'profiles':profiles})

pdf/templates/pdf/accept.html
<!DOCTYPE html>
{% load static  %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <title>Document</title>
    <link rel="stylesheet" href="{% static 'pdf/pdf.css' %}">
</head>
<body>

  <nav class="navbar navbar-expand-lg navbar-light bg-light navbar-custom  ">
    
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
  
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item active">
          <a class="nav-link" href="{% url 'pdf:list' %}">List <span class="sr-only">(current)</span></a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#">Faceboob</a>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            Dropdown
          </a>
          <div class="dropdown-menu" aria-labelledby="navbarDropdown">
            <a class="dropdown-item" href="#">Action</a>
            <a class="dropdown-item" href="#">Another action</a>
            <div class="dropdown-divider"></div>
            <a class="dropdown-item" href="#">Something else here</a>
          </div>
        </li>
        <li class="nav-item">
          <a class="nav-link disabled" href="#" tabindex="-1" aria-disabled="true">Disabled</a>
        </li>
      </ul>
      <form class="form-inline my-2 my-lg-0">
        <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
      </form>
    </div>
  </nav>





</div>




    <div class="container">
      <div class="row">
        <div class="col-md-7">

          <form method="POST">
            {% csrf_token %}
            <div class="form-group">
              <label for="">Name</label>
              <input type="text" class="form-control" id="name" name="name" >
            
            </div>
    
    
            <div class="form-group">
                <label for="">Email</label>
                <input type="text" class="form-control" id="email" name="email" >
              </div>
    
    
    
              <div class="form-group">
                <label for="">Phone</label>
                <input type="text" class="form-control" id="phone" name="phone" >
              </div>
    
    
              <div class="form-group">
                <label for="">About You</label>
                <textarea type="texta" class="form-control" id="summary" name="summary" ></textarea>
            
    
    
              <div class="form-group">
                <label for="">Degree</label>
                <input type="text" class="form-control" id="degree" name="degree" >
              </div>
    
              <div class="form-group">
                <label for="">School</label>
                <input type="text" class="form-control" id="school" name="school" >
              </div>
    
              <div class="form-group">
                <label for="">University</label>
                <input type="text" class="form-control" id="university" name="university" >
              </div>
    
    
              <div class="form-group">
                <label for="">Privious work</label>
                <textarea type="texta" class="form-control" id="privious_work" name="privious_work" ></textarea>
              </div>
    
    
              <div class="form-group">
                <label for="">Sills</label>
                <textarea type="texta" class="form-control" id="skills" name="skills" ></textarea>
              </div>
    
    
    
           
            <div class="form-group">
              <label for="exampleInputPassword1">Password</label>
              <input type="password" class="form-control" id="exampleInputPassword1" placeholder="Password">
            </div>
            
            <button type="submit" class="btn btn-primary">Submit</button>
          </form>



        </div>
      </div>
    </div>
    
</body>
</html>

pdf/templates/pdf/list.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <title>Document</title>
</head>
<body>
    <div class="container">
        <div class="row col-md-5">
            <div class="col-md-12">
                <h2>Cv Database Profile List</h2>
            </div>
        </div>
        {%for profile in profiles %}
        <div class="row">
            <div class="col-md-6">
                {{profile.name}}
            </div>

            <div class="col-md-6">
               <a href="/{{profile.id}}" class="btn-warning">Download CV</a>
            </div>

        </div>
        <hr/>
        {% endfor %}
    </div>
</body>
</html>

pdf/templates/pdf/resume.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h2>{{user_profile.name}}</h2>
    <h2>{{user_profile.email}}</h2>
    <h2>{{user_profile.phone}}</h2>
    <hr/>
    <br/>
    <h2>Summary</h2>
     <p>{{user_profile.summary}}</p>
     <hr/>

     <h2>Skills</h2>
     <p>{{user_profile.skills}}</p>
     <hr/>


     <h2>Education</h2>

     <ul>
         <li>Schooling: {{user_profile.school}}</li>
         <li> {{user_profile.degree}} from {{user_profile.university}}</li>
     </ul>
     <hr>
     <h2>Privious_work</h2>
     <p>{{user_profile.privious_work}}</p>
   

    
</body>
</html>